#%RAML 1.0
title: User API
version: v1
mediaType: application/json
baseUri: hb://media-upload

types:
  CreateMediaVersions:
    type: object
    properties:
      original_url: string

  MediaStatus:
    enum: [scheduled,progress,normal,failed,deleted]
  Media:
    type: object
    properties:
      media_id: string
      original_url: string
      versions?:
        type: object
        example: |
          {
            "1024x768": "https://cdn.example.com/abc/def/1024.jpeg",
            "320x240": "https://cdn.example.com/abc/def/320.jpeg"
          }
      status: MediaStatus

/media-files:
  post:
    body: CreateMediaVersions
    responses:
      201:
        body: Media

/media-files/{media_id}:
  uriParameters:
    media_id: string
  get:
    responses:
      202:
        body: Media
      200:
        body: Media
